Remove estilo de links e outros ajustes
gabrnunes/orbita pull request #8
Opened 2022-11-15 12:03 UTC by rghedin

Outros ajustes:

* Adiciona cursor: pointer ao botão de reportar post.
* Estende o max-width do orbita-header para 100%.

2022-11-15 12:05 UTC, rghedin commented
Sintam-se à vontade para arrumar/modificar ou ignorar este pull request. Sou bem ruim com CSS (com tudo de programação, na real).

2022-11-17 00:37 UTC, claromes commented on src/scss/main.scss
>    a {
```suggestion
  div a {
    margin-left: 1rem;
    display: inline;
    line-height: 1;

    &:visited {
      color: var(--color-link);
    }

    &:hover {
      color: var(--color-link-states);
    }
  }
```

2022-11-17 00:39 UTC, claromes requested changes

2022-11-17 00:39 UTC, claromes commented on src/scss/main.scss
>    a {
Sugiro esse código pra que o menu possa seguir a regra de links do tema, mas sem ser afetado pelo "visited" e não mude de cor.

2022-11-17 19:22 UTC, gabrnunes approved these changes

2022-11-17 19:22 UTC, merged